apiVersion: apps/v1
kind: Deployment
metadata:
  name: log4j
  namespace: backend
  labels:
    app: log4j
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log4j
  template:
    metadata:
      labels:
        app: log4j
    spec:
      containers:
      - name: log4j
        image: xniapdev/log4j-poc:tel
        ports:
        - containerPort: 4412
---
apiVersion: v1
kind: Service
metadata:
  name: log4j-service
  namespace: log4j
spec:
  selector:
    app: log4j
  type: NodePort
  ports:
  - port: 4441